### ISSUE TITLE
Portainer Port

### ISSUE THREAD

**Issue by zmink-pxc** [PLCnext/EdgeDevices#2]
Hi, I've installed the app as instructed but I am unable to determine if Portainer is running.  Is there a default port that Portainer is run with in the app?  In an ssh session with the device, the docker cli shows no images installed and no containers running.  Thanks for your help

**Comment by DMantler** [comment]
Hi, 
the [Docker-Portainer App for EPC](https://www.plcnextstore.com/eu/app/1565) is default running on Port 9000.
If you can't reach port 9000 (default X3: 192.168.1.10:9000 ) after installing the App, could you please try to deinstall the App via the WBM, restart your device and try to reinstall the App?

I've added the default port information more visible into the PLCnext Store App as well.

Happy new year and best regards!
